# Use root/example as user/password credentials
version: '3.1'

services:
  xinlianye-mysql:
    image: mysql:8
    container_name: xinlianye-mysql
    environment:
      - MYSQL_DATABASE=xinlianye
      - MYSQL_USER=xinlianye
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
      - TZ=UTC
    command:
      --default_authentication_plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql_custom.conf:/etc/mysql/mysql.conf.d/mysql_custom.cnf
    ports:
      - "24406:3306"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
